### ISSUE TITLE
Feature request: Android firefox compatibility

### ISSUE THREAD

**Issue by Baramanga** [kheina-com/Blue-Blocker#132]
I think it would be great if you can make the extension compatible with android firefox browser!

**Comment by DanielleMiu** [comment]
it actually should be, and I mark it as such when I upload the packages, but it doesn't allow you to install it. I don't know why

**Comment by insin** [comment]
You can only install the very short list of [recommended extensions](https://addons.mozilla.org/en-US/android/) in Firefox on Android.

You _can_ install other extensions in Firefox Beta and Firefox Nightly, but you have to create a custom [collection](https://support.mozilla.org/en-US/kb/how-use-collections-addonsmozillaorg) containing the extensions you want and [configure your browser with it](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/) (this post is about Nightly but this feature is now in Beta) in order to do so 😿

**Comment by DanielleMiu** [comment]
seems like this isn't really on us to fix, unfortunately. hopefully firefox enables all addons in the main browser soon. in the mean time you can try the suggestions [mentioned above](#issuecomment-1595667378), or you can use the kiwi browser, which I have seen a few people mention on twitter as being able to load the extension, though I don't use it myself.
