### ISSUE TITLE
Import block list into queue

### ISSUE THREAD

**Issue by SamChou19815** [kheina-com/Blue-Blocker#145]
Since the blocker already maintains a queue, it should be relatively straight-forward to add support for importing a block list like https://github.com/esqueer/twitter_blue_blocklist.

Happy to contribute if you like the idea.

**Comment by DanielleMiu** [comment]
similar and should be done at the same time: import/export of the unblocked list/safelist

**Comment by DanielleMiu** [comment]
there were a lot of reacts to the PR that adds this feature, so I want to have a little warning, I did test it with the full 200-some thousand block list, but be VERY careful adding that. it will slow down the extension significantly because it loads the whole list into memory to unqueue a user. it could probably handle up to 10k fairly easily

some more info and a fix in #170

**Comment by SamChou19815** [comment]
Thanks a lot, even an non-performing one can be helpful.

There are only 86400 seconds a day, assuming a block rate of 1 in 10s, then I can still block 8640 blues a day. Since I already need to write a script to transform the list, adding a partitioning step and manually intervene once a day doesn't sound bad at all!

**Comment by DanielleMiu** [comment]
> Thanks a lot, even an non-performing one can be helpful.
> 
> There are only 86400 seconds a day, assuming a block rate of 1 in 10s, then I can still block 8640 blues a day. Since I already need to write a script to transform the list, adding a partitioning step and manually intervene once a day doesn't sound bad at all!

wouldn't recommend 10s, twitters gotten more trigger-happy with bans and logouts. I use 20-30s
