### ISSUE TITLE
Blue Blocker does not block anyone!

### ISSUE THREAD

**Issue by bitchtownusa** [kheina-com/Blue-Blocker#188]
I am on Version 0.3.4 of BlueBlocker and Version 94.0.2 of Firefox. I have attached the error section from the Firefox console but let me know if you need any more info!
![image](https://github.com/kheina-com/Blue-Blocker/assets/138406254/080297b6-304e-43a5-b970-696de9bd4890)

**Comment by DanielleMiu** [comment]
so it looks like that error at the top `(intermediate value).storage.local.onChanged is undefined` is the error you're experiencing. this is because your firefox version is pretty far out of date, the `onChanged` listener was added in firefox 101 https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/onChanged

are you using ESR? what's your os?

**Comment by bitchtownusa** [comment]
I'm on Windows 11 and Firefox shows I am on the latest version. This is what it shows when I go into settings to update Firefox.
![image](https://github.com/kheina-com/Blue-Blocker/assets/138406254/02c4dccd-96ec-4610-892b-01249aa18adc)

**Comment by bitchtownusa** [comment]
Oh my god. I downloaded the Firefox installer and it updated finally and Blue Blocker works now. Thank you very much! Issue resolved.

**Comment by DanielleMiu** [comment]
haha glad I could help. I'll probably add a min version or something to avoid this in the future
