### ISSUE TITLE
Already muted accounts get queued again

### ISSUE THREAD

**Issue by rdtbk** [kheina-com/Blue-Blocker#198]
Hi,

I use the following setting: "mute users instead of blocking them"

Every time I scroll over a muted users comment, he gets queued again.

And the blocked counter goes +1 - for now the counter says 24k and i muted about 12k users.

Is there a way to optimize this?

Thanks!

**Comment by kheina** [comment]
I think you've found a bug that's been hidden since this feature was added. blue blocker uses the twitter api's `user.legacy.blocking` field to determine whether or not to skip this particular user because they've already been blocked

https://github.com/kheina-com/Blue-Blocker/blob/f6db6561f89b8f3c29a9a181b6d81534208eab09/src/shared.ts#L379-L381

however, I don't think we ever added a catch for if the user is using the mute option and the user has already has them muted. in fact, I'm not sure if the twitter api returns this information, though I think it should.

given that [the current lord of twitter has deemed blocking should be removed from the platform](https://twitter.com/elonmusk/status/1692558414105186796), fixing this should be prioritized.
