### ISSUE TITLE
Dependencies: switch from html-minifier to html-minifier-terser

### ISSUE THREAD

**Issue by cooljeanius** [kheina-com/Blue-Blocker#323]
See discussion in kangax/html-minifier#1135. Note that I'm not sure if this alternative is a perfect drop-in replacement for the existing dependency or not. Also I'm not sure what switching would mean we'd have to do with the version number.

**Comment by cooljeanius** [comment]
Blame makes it look like @rougetimelord added the dependency in #312, but digging a little bit deeper reveals that @kheina actually added it in #287

**Comment by DanielRuf** [comment]
I suggest reading my acomments and especially https://github.com/kangax/html-minifier/issues/1135#issuecomment-2453437884 - because switching to `html-minifier-terser` will not fix this.

**Comment by rougetimelord** [comment]
> I suggest reading my comments and especially [kangax/html-minifier#1135 (comment)](https://github.com/kangax/html-minifier/issues/1135#issuecomment-2453437884) - because switching to `html-minifier-terser` will not fix this.

I believe that we switched to the terser branch because it was more recently updated.

I'm also not really sure if we are affected by the vulnerability, our only usage of html-minifier is to minify HTML files within a build step. The extension itself does not use html-minifier, and we do not have a way for users to control the input to the minify function.
