### ISSUE TITLE
Have to manually enable permission to access twitter? (on Firefox)

### ISSUE THREAD

**Issue by sourcejedi** [kheina-com/Blue-Blocker#42]
Sorry, I don't know what the reason is.

But when I add this extension to my Firefox, it doesn't work to start with.  If I pin the extension icon, it gets a blue dot and a tooltip saying I need to grant permissions.  If I go to manage this specific extension, and go to permissions, the permissions for twitter.com are not enabled.  Enabling these permissions then lets the extension work as expected.

I might have previously installed and then removed the extension. Maybe that caused it?

**Comment by DanielleMiu** [comment]
this is the first time I've heard of this. I'm hesitant to think that this is an extension issue, it sounds like you might have some strict privacy settings enabled in your firefox or something. very weird

**Comment by DanielleMiu** [comment]
so, I think this is because of the switch from manifest version 2 to manifest version 3. unfortunately, firefox ESR does not have support for manifest v3 yet, so we just switched back to v2, so you'll likely get a check like this again, but it should be the last time for a while.

related: https://github.com/kheina-com/Blue-Blocker/issues/39
