### ISSUE TITLE
Block requests queued before signout erroring when signed back in

### ISSUE THREAD

**Issue by thefncrow** [kheina-com/Blue-Blocker#46]
I ran into an issue where I was having a queue of blocks processing when I was logged out (probably block rate limiting), but when I logged back in and tried to kick it off again, all blocks that were trying to process were returning 403 errors, the body of the response being that the CSRF header didn't match.

(I'm going to note in advance that I'm in that zone here of "knows enough to be dangerous", so, apologies if I've missed something about how this works and my theories are a little bunk.)

From the investigation I was able to do, what I think happened is that the blocks were queued with the header block from one session, including the CSRF token, but after signing back in, processing started again sending those requests using the cached but now invalid CSRF token.

(My investigation here was a little limited because I'm kinda wary about letting the thing just keep flying sending invalid block requests.)

I was able to get blocking working again by removing and reinstalling the extension in chrome, which suggests to me that I probably could have also let it send however many failed block requests and it'd eventually come back to me.  However, there might need to be some sort of recovery here that doesn't require refreshing the extension or having to wait for the queue to stream out all the doomed requests, like a manual button for clearing the queue, something that watches the return of the block requests firing to handle when errors start happening, etc.

**Comment by DanielleMiu** [comment]
yup, as you correctly found out, this is due to the csrf token being incorrect between issuing request and the current cookie state. [`v0.2.3`](https://github.com/kheina-com/Blue-Blocker/pull/38) already has a fix in place for this by pulling the csrf from the cookie directly before making the block request.

https://github.com/kheina-com/Blue-Blocker/pull/38/files#diff-54ae40e35c503792f71f237cb5dec82d1240eba383b1d80e454482c1563f605dR263-R270

I'll close this issue once it's deployed
