### ISSUE TITLE
Clarification of verification blocking by "other means" and "affiliations".

### ISSUE THREAD

**Issue by hyenatown** [kheina-com/Blue-Blocker#62]
Would it be possible to include what exactly these switches do? Either in the readme or as a hover tooltip in the extension window?

**Comment by DanielleMiu** [comment]
that's a very good point. previously "verified through other means" just meant people who were actually verified, but also bought blue. since that's gone away I guess it doesn't really make sense anymore. affiliations is the gold checkmark for businesses and whatnot, that could probably be worded better

**Comment by DanielleMiu** [comment]
fixed by https://github.com/kheina-com/Blue-Blocker/pull/99
